swagger: '2.0'
info:
  description: Graphic Markup API
  version: 1.0.0
  title: Graphic Markup API
basePath: /api/v1
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json

tags:
  - name: Graphic Markup
paths:
  '/markup/{id}':
    get:
      tags:
        - Graphic Markup
      summary: Get existing graphic markup data
      description: Get existing graphic markup data
      operationId: getGraphicMarkup
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: sort
          in: query
          type: string
          required: false
        - name: location
          in: query
          type: string
          required: false
        - name: page
          in: query
          type: integer
          required: false
        - name: limit
          in: query
          type: integer
          required: false
      responses:
        '200':
          description: response containing graphic markup data
          schema:
            $ref: '#/definitions/markupResponse'
definitions:
  markupResponse:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/markupData'
      count:
        type: number
      code:
        type: number
  markupData:
    type: object
    properties:
      in_frame:
        type: number
      out_frame:
        type: number
      duration:
        type: number
      content:
        type: object
        properties:
          value:
            type: array
            items:
              type: string
          labels:
            type: array
            items:
              type: string
          graphics_type_value:
            type: array
            items:
              type: string
          location:
            type: array
            items:
              type: string
          sample_frame:
            type: integer
      data_type_id:
        type: string
      tech_id:
        type: string
        

